core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login_success,name = 'login_success'),
    path('accounts/', include('user.urls')),#Account or user part
    path('sales/',include('sales.urls')),
    path('production/',include('production.urls')),
    path('report/', include('report.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^report_builder/', include('report_builder.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

sales/urls.py
from typing import Pattern
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from .views import *

urlpatterns = [
    #Price Table part
    path('pricetable/',PriceTableListView.as_view(), name = 'price_table_list'),
    path('pricetable/create/',PriceTableCreateView.as_view(), name = 'price_table_create'),
    path('pricetable/<int:pk>/update/',PriceTableUpdateView.as_view(), name = 'price_table_update'),
    path('pricetable/<int:pk>/delete/',PriceTableDeleteView.as_view(), name = 'price_table_delete'),
    #orders part
    path('order/',login_required(OrderListView.as_view()), name = 'orders_list'),
    #path('order/create/',OrderCreateView.as_view(), name = 'orders_create'),
    path('order/<int:pk>/create/',OrderCreateView.as_view(), name = 'orders_create'),
    #path('order/<int:pk>/create/',OrderCreate, name = 'orders_create'),
    # path('order/<int:pk>/update/',OrderUpdateView.as_view(), name = 'orders_update'),
    path('order/<int:pk>/update/',OrderUpdate, name = 'orders_update'),
    #path('order/<int:pk>/delete/',OrderDeleteView.as_view(), name = 'orders_delete'),
    path('order/<int:pk>/delete/',OrderDelete, name = 'orders_delete'),
    path('order/<int:pk>/details/', OrderDetailView.as_view(), name = 'order_details'),

    #Company Part
    path('company/',CompanyListView.as_view(), name = 'company_list'),
    path('company/create/',CompanyCreateView.as_view(), name = 'company_create'),
    path('company/<int:pk>/update/',CompanyUpdateView.as_view(), name = 'company_update'),
    path('company/<int:pk>/delete/',CompanyDeleteView.as_view(), name = 'company_delete'),
    #Product Part
    path('product/',ProductListView.as_view(), name = 'product_list'),
    path('product/<int:pk>/details/',ProductDetailView.as_view(), name = 'product_details'),
    path('product/create/',ProductCreateView.as_view(), name = 'product_create'),
    path('product/<int:pk>/update/',ProductUpdateView.as_view(), name = 'product_update'),
    path('product/<int:pk>/delete/',ProductDeleteView.as_view(), name = 'product_delete'),
]

sales/models.py
from email.policy import default
from enum import unique
import random
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django_resized import ResizedImageField
from django.utils import timezone
import datetime
import time
from django.contrib.auth import get_user_model
User = get_user_model()

from user.models import CustomUser
# Create your models here.

class PriceTable(models.Model):
    product_id = models.ForeignKey("Product", on_delete=models.CASCADE)
    rm_price = models.ForeignKey("production.RawMaterial", on_delete=models.CASCADE)
    shipping_cost = models.FloatField(null = True,default=0)
    delivery_cost = models.FloatField(null = True,default=0)
    production_cost = models.FloatField(null=True,default=0)
    others_cost = models.FloatField(null = True,default=0)
    def __str__(self):
        return self.product_id

class Product(models.Model):
    product_name = models.CharField(max_length = 30, null=True)
    product_price = models.FloatField(default = 0, null=True)
    product_desc = models.CharField(max_length = 300, null=True)
    product_qty = models.PositiveIntegerField(default = 1, null=True)
    product_pic = ResizedImageField(upload_to = 'Product/',null=True, blank = True )

    def __str__(self):
        return self.product_name


class Order(models.Model):

    # def new_ref():
    #     not_unique = True
    #     while not_unique:
    #         unique_ref = random.randint(1000000000,9999999999)
    #         if not Order.objects.filter(order_unique_id = unique_ref):
    #             not_unique=False
    #     return str(unique_ref)    

    # order_unique_id = models.CharField(max_length=10,blank=True, editable=False, unique=True,default = new_ref)
    order_name = models.CharField(max_length = 30, null=True)
    order_items = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    order_creator = models.ForeignKey(User, on_delete=models.CASCADE)
    order_qty = models.IntegerField(default=1, null=True)
    order_details = models.TextField()
    payment_status = models.BooleanField(default=False)
    order_status_choice = (("New","New"),("Processing","Processing"),("Delivered","Delivered"),("Cancelled","Cancelled"))
    order_status = models.CharField(max_length=10,choices=order_status_choice, default="New")
    order_total_price = models.FloatField(null=True)
    order_date = models.DateField(default= timezone.now)
    delivery_date = models.DateField(null = True)

    
    def __str__(self):
        return self.order_name

    def placeOrder(self):
        self.save()
  
    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')


class Company(models.Model):
    business_name = models.CharField(max_length = 30, null=False)
    business_address = models.CharField(max_length= 300, null=False)
    business_orders = models.ForeignKey(Order,  on_delete=models.CASCADE, null=True)
    business_bank_account = models.CharField(max_length=30,null=True)
    business_website = models.URLField(default="https://www.",null=True)
    business_email = models.EmailField(null = True, default="business_name@gmail.com")
    business_contact_number = models.CharField(max_length=14,null=True)
    business_contact_person = models.CharField(max_length=80,null=False)
    business_status = models.CharField(max_length=50,null=False, default="National")
    
    def __str__(self):
        return self.business_name

sales/forms.py
from dataclasses import field, fields
from email.policy import default
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django.utils import timezone
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_name','order_qty','order_details','order_date',]

class OrderUpdateForm(forms.ModelForm):
    delivery_date = forms.DateField(required=False, help_text='Will be given by the Admin only')
    order_status_choice = (("New","New"),("Processing","Processing"),("Delivered","Delivered"),("Cancelled","Cancelled"))
    order_status = forms.ChoiceField(required=False, choices = order_status_choice)
    order_total_price = forms.FloatField(required=False)
    class Meta:
        model = Order
        fields = ['order_status', 'order_qty','order_details','order_items','delivery_date','order_total_price']

sales/views.py
from ast import Delete
from asyncio.windows_events import NULL
from itertools import product
from mimetypes import init
from pyexpat import model
import re
from typing import List
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.template import context
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from django.http import HttpResponse, HttpResponseRedirect
from core.views import login_success
from sales.forms import OrderCreateForm, OrderUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Order,Company, PriceTable,Product
from django.urls import reverse_lazy


# Create your views here.
#PRice Table Part is here
#order views part
class PriceTableListView(LoginRequiredMixin,ListView):
    model = PriceTable
    success_url = reverse_lazy('price_table_list')
    template_name = 'sales/pricetablelist.html'

class PriceTableCreateView(LoginRequiredMixin, CreateView):
    model = PriceTable
    fields = '__all__'
    success_url = reverse_lazy('price_table_list')
    template_name = 'sales/pricetablecreate.html'

class PriceTableUpdateView(LoginRequiredMixin, UpdateView):    
    model = PriceTable
    fields = '__all__'
    success_url = reverse_lazy('price_table_list')
    template_name = 'sales/pricetableupdate.html'

class PriceTableDeleteView(LoginRequiredMixin, DeleteView):
    model = PriceTable
    fields = '__all__'
    success_url = reverse_lazy('price_table_list')
    template_name = 'sales/pricetabledelete.html'

#ORDER views part
class OrderListView(LoginRequiredMixin,ListView):
    model = Order
    success_url = reverse_lazy('orders_list')
    template_name = 'sales/orders.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.groups.name == 'Buyer':
            context['object_list'] = Order.objects.filter(order_creator = self.request.user.id)
        else:context["object_list"] = Order.objects.all()
        return context

class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    

class OrderCreateView(LoginRequiredMixin,CreateView):
    model = Order
    form_class = OrderCreateForm
    success_url = reverse_lazy('orders_list')
    template_name = 'sales/orderscreate.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product"] =Product.objects.values_list('product_qty', flat=True).get(pk = self.kwargs.get('pk'))
        return context
    

    def stock_update(pk,order_quantity):
        product = Product.objects.get(pk=pk)
        product.product_qty = product.product_qty-order_quantity
        product.save()
    
    def form_valid(self, form):
        #for Stock update facility
        OrderCreateView.stock_update(self.kwargs.get('pk'), form.cleaned_data['order_qty'])
        #for placing order
        Order = form.save(commit=False)
        Order.order_creator =  self.request.user
        form.instance.order_items = Product.objects.get(pk=self.kwargs.get('pk'))
        form.instance.order_total_price = Product.objects.values_list('product_price', flat=True).get(pk=self.kwargs.get('pk'))* form.cleaned_data['order_qty']
        Order.save()
        form.save()
        return redirect('orders_list')
     
    
# class OrderUpdateView(LoginRequiredMixin, UpdateView):    
#     model = Order
#     fields = ['order_items', 'order_details','order_qty', 'order_status']
#     success_url = reverse_lazy('orders_list')
#     template_name = 'sales/ordersupdate.html'
#     def form_valid(self, form):
        
#         #for Stock update facility
#         # OrderCreateView.stock_update(self.kwargs.get('pk'), form.cleaned_data['order_qty'])
#         #for placing order
        
#         Order = form.save(commit=False)
#         print(self.kwargs.get('order_qty'))
#         print(form.cleaned_data['order_qty'])
#         Order.save()
#         form.save()
        
#         return redirect('orders_list')


# class OrderDeleteView(LoginRequiredMixin, DeleteView):
#     model = Order
#     fields = '__all__'
#     success_url = reverse_lazy('orders_list')
#     template_name = 'sales/ordersdelete.html'

#     def delete(self, *args, **kwargs):
#         print(self.instance.id)
#         print("Hello world")


# @login_required
# def OrderCreate(request,pk):
#     context = {}
#     form = OrderCreateForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect("order_list")
#     context['form'] = form
#     return render(request, "sales/orderscreate.html")


class OrderDetailView(LoginRequiredMixin,DetailView):
    model = Order
    template_name = 'sales/orderdetails.html'

@login_required
def OrderUpdate(request, pk):
    context = {}
    obj = get_object_or_404(Order, id = pk)
    product = Product.objects.get(pk = obj.order_items.pk)
    product.product_qty = product.product_qty + obj.order_qty
    form = OrderUpdateForm(request.POST or None, instance = obj)
    if form.is_valid():
        product.product_qty = product.product_qty - form.instance.order_qty
        form.instance.order_total_price =obj.order_items.product_price * obj.order_qty
        product.save()
        form.save()
        return redirect("orders_list")
    context['form'] = form
    return render(request, 'sales/ordersupdate.html', context)

@login_required
def OrderDelete(request, pk):    
    order = get_object_or_404(Order, id = pk)
    context = {'order_name' : order.order_name}
    PDkey = order.order_items.pk
    if request.method == "POST":
        product = Product.objects.get(pk = PDkey)
        product.product_qty = product.product_qty + order.order_qty
        product.save()
        order.delete()
        return HttpResponseRedirect("/")
    return render(request,'sales/ordersdelete.html',context)
    


#company
class CompanyListView(LoginRequiredMixin, ListView):
    model = Company
    template_name = 'sales/company.html'

class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    fields = '__all__'
    success_url = reverse_lazy('company_list')
    template_name = 'sales/companycreate.html'

class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    fields = '__all__'
    success_url = reverse_lazy('company_list')
    template_name = 'sales/companyupdate.html'

class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    fields = '__all__'
    success_url = reverse_lazy('company_list')
    template_name = 'sales/companydelete.html'






#Product View part
class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    success_url = reverse_lazy('product_list')
    template_name = 'sales/products.html'
    

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('product_list')
    template_name = 'sales/productscreate.html'

class ProductUpdateView(LoginRequiredMixin, UpdateView):    
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('product_list')
    template_name = 'sales/productsupdate.html'

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('product_list')
    template_name = 'sales/productsdelete.html'

class ProductDetailView(DetailView):
    model = Product
    fields = '__all__'
    template_name = "sales/productdetails.html"




    

templates/sales/company.html
{% extends 'base.html' %}

{% block content %}
<div class="">
    <div class="row">
        <div class="col">
            <div class="card card-custom gutter-b ">
                <div class="card-header d-flex">
                    <div class="card-title ">
                        <h3 class="card-label">Company List</h3>
                    </div>
                    <div class="card-toolbar ml-auto">
                        <a href="{% url 'company_create' %}" class="btn btn-info">Add New</a>
                    </div>
                </div>
                <div class="card-body">
                    {% comment %}{% endif %}{% endcomment %}
                    {% comment %}{% endcomment %}
                    <!-- begin: Table -->
                    <div class="table-responsive">
                        <table class="table" id="kt_datatable" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Company</th>
                                    <th>Address</th>
                                    <th>Product</th>
                                    <th>Account.</th>
                                    <th>Webpage</th>
                                    <th>Email</th>
                                    <th>Contact No.</th>
                                    <th>Representative</th>
                                    <th>Status</th>
                                    <th style="width: 180px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                {% for company in object_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ company.business_name }}</td>
                                    <td>{{ company.business_address }}</td>
                                    <td>{{ company.business_product }}</td>
                                    <td>{{ company.business_bank_account }}</td>
                                    <td>{{ company.business_website | truncatechars:10 }}</td>
                                    <td>{{ company.business_email | truncatechars:10}}</td>
                                    <td>{{ company.business_contact_number }}</td>
                                    <td>{{ company.business_contact_person }}</td>
                                    <td>{{ company.business_status }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-light-warning"
                                            href="{% url 'company_update' company.pk %}"><i class="far fa-edit btn btn-success"></i>
                                        </a>
                                        <a class="btn btn-sm btn-light-danger"
                                            href="{% url 'company_delete' company.pk %}"><i
                                                class="far fa-trash-alt btn btn-danger"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!--end: Datatable-->
                    {% comment %}{% endcomment %}
                </div>
                <div class="card-footer">
                    {% comment %}{% endcomment %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/sales/companycreate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}
Profile Update
{% endblock title %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Company or Buyer</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Create New buyer or company!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-block">Create</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'Dashboard' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/sales/companydelete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}
Company Delete
{% endblock title %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Delete a Company</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Sure to delete "{{ company.business_name }}" from list?!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-block">Delete!</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'Dashboard' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/sales/companyupdate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}
Profile Update
{% endblock title %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Update Your Buyers information</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Update buyers!!!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-block">Update</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'company_list' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/sales/orders.html
{% extends 'base.html' %}

{% block content %}
<div class="">
    <div class="row">
        <div class="col">
            <div class="card card-custom gutter-b ">
                <div class="card-header d-flex">
                    <div class="card-title">
                        <h3 class="card-label">Orders List</h3>
                    </div>
                    {% comment %} <div class="card-toolbar ml-auto">
                        <a href="{% url 'orders_create' %}" class="btn btn-info">Add New</a>
                    </div> {% endcomment %}
                </div>
                <div class="card-body">
                    {% comment %} {% if filter %}
                    {% include 'includes/filter.html' %}
                    {% endif %} {% endcomment %}
                    {% if object_list %}
                    <!--begin: Table-->
                    <div class="table-responsive">
                        <table class="table" id="kt_datatable" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Order</th>
                                    <th>Items</th>
                                    <th>Quantity</th>
                                    <th>Details</th>
                                    {% if user.groups.name == 'Admin' %}
                                    <th>Status</th>
                                    <th>Customer</th>
                                    <th>Total</th>
                                    <th>Ordering Date</th>
                                    {% endif %}
                                    <th>Payment</th>
                                    <th>Delivery Date</th>
                                    <th style="width: 180px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                {% for order in object_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ order.order_name | truncatechars:10}}</td>
                                    <td>{{ order.order_items }}</td>
                                    <td>{{ order.order_qty }}</td>
                                    <td>{{ order.order_details | truncatechars:10}}</td>
                                    {% if user.groups.name == 'Admin' %}
                                    <td>{{ order.payment_status }}</td>
                                    <td>{{ order.order_status }}</td>
                                    <td>{{ order.order_creator }}</td>
                                    <td>{{ order.order_date }}</td>
                                    {% endif %}
                                    <td>{{ order.order_total_price }}</td>
                                    <td>{{ order.delivery_date }}</td>
                                    <td>{% if user.groups.name == 'Admin' or order.order_status == 'New' %}
                                        <a class="btn btn-sm btn-dark-warning"
                                            href="{% url 'orders_update' order.pk %}"><i class="far fa-edit btn btn-success"></i>
                                        </a>
                                        
                                        <a class="btn btn-sm btn-light-danger"
                                            href="{% url 'orders_delete' order.pk %}"><i
                                            class="far fa-trash-alt btn btn-danger"></i></a>
                                        {% elif order.order_status != 'New' %}
                                        <a class="btn btn-sm btn-light-danger"
                                        href="{% url 'order_details' order.pk %}"><i
                                        class=" fa fa-eye btn btn-success">
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!--end: Datatable-->
                    {% else %}
                    {% include 'includes/no_data_found.html' %}
                    {% endif %} 
                </div>
                <div class="card-footer">
                    {% comment %} {% include 'includes/pagination.html' %} {% endcomment %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/sales/orderscreate.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Order
Placement {% endblock title %} 
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Place a Order!!!</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Place Order!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {% comment %} {{ form | crispy }} {% endcomment %}
                    {{ form.order_name | as_crispy_field }}
                    {% comment %} {{ form.order_qty | as_crispy_field }} {% endcomment %}
                    <label>Order Quantity<sup>*</sup></label>
                    <div class="">
                      <input type="number" name="order_qty" min="1" max="{{product}}" class="numberinput form-control" required="" id="id_order_qty">
                    </div>
                    {{ form.order_details | as_crispy_field }}
                    {{ form.order_date | as_crispy_field }}
                    <button type="submit" class="btn btn-success btn-block">Create</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'login_success' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/sales/ordersupdate.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Order
Update {% endblock title %} {% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
    <h1 class="h3 mb-0 text-gray-800">Update your order</h1>
  </div>

  <!-- Main Content Here -->
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">
                Only update when possible!!!
              </h1>
            </div>
            <form method="POST" >
              {% csrf_token %}
                {% if user.groups.name == 'Admin' %}
                {{ form.order_status | as_crispy_field }}
                {% endif %}
                {{ form.order_items | as_crispy_field }}
                {{ form.order_details | as_crispy_field }}
                {{ form.order_qty | as_crispy_field }}
                {% if user.groups.name == 'Admin' %}
                {{ form.delivery_date | as_crispy_field }} 
                {% endif %}
                <button type="submit" class="btn btn-success btn-block">
                  Update
                </button>
              </form>

             
            <hr />
            <div class="text-center">
              <a class="small" href="{% url 'orders_list' %}">Back</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
{% endblock content %}