core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login_success,name = 'login_success'),
    path('accounts/', include('user.urls')),#Account or user part
    path('sales/',include('sales.urls')),
    path('production/',include('production.urls')),
    path('report/', include('report.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^report_builder/', include('report_builder.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

report/urls.py
from django.urls import path, include, re_path
# from django.conf.urls import url
from .views import BuyerReportView, DashboardView, MonthlyBenifitCreateView, MonthlyBenifitListView, MonthlyBenifitUpdateView, ProductionReportView, SalesReportView, SearchView, SupplierReportView
urlpatterns = [
    path('salesreport/', SalesReportView.as_view(), name='sales_report'),
    path('productionreport/', ProductionReportView.as_view(), name='production_report'),
    path('dashboard/', DashboardView.as_view(), name='Dashboard'),
    path('buyerreport/', BuyerReportView.as_view(), name = 'buyer_report'),
    path('supplierreport/', SupplierReportView.as_view(), name = 'supplier_report'),
    path('search/',SearchView.as_view(),name='search'),
    path('monthlybenifitcreate/', MonthlyBenifitCreateView.as_view(),name='monthlybenifit_create'),
    path('<int:pk>/monthlybenifitupdate/', MonthlyBenifitUpdateView.as_view(), name='monthlybenifit_update'),
    path('monthlybenifitlist/', MonthlyBenifitListView.as_view(),name='monthlybenifit_list'),
]

report/models.py
from sys import maxsize
from tabnanny import verbose
from django.db import models
from django.forms import FloatField
from django.core.validators import MaxValueValidator,MinValueValidator
# Create your models here.
class MonthlyBenifit(models.Model):
    year = models.SmallIntegerField(verbose_name="Year", validators=([MaxValueValidator(9999),MinValueValidator(2000)]))
    month = models.SmallIntegerField(verbose_name="Month", validators=([MaxValueValidator(12),MinValueValidator(1)]))
    earnings = models.FloatField(verbose_name="Earning Track", default=0)

    class Meta:
        unique_together = ('year','month')

    def __str__(self) -> str:
        return ("Year("+str(self.year)+")-Month("+str(self.month)+")")

sales/models.py
from email.policy import default
from enum import unique
import random
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django_resized import ResizedImageField
from django.utils import timezone
import datetime
import time
from django.contrib.auth import get_user_model
User = get_user_model()

from user.models import CustomUser
# Create your models here.

class PriceTable(models.Model):
    product_id = models.ForeignKey("Product", on_delete=models.CASCADE)
    rm_price = models.ForeignKey("production.RawMaterial", on_delete=models.CASCADE)
    shipping_cost = models.FloatField(null = True,default=0)
    delivery_cost = models.FloatField(null = True,default=0)
    production_cost = models.FloatField(null=True,default=0)
    others_cost = models.FloatField(null = True,default=0)
    def __str__(self):
        return self.product_id

class Product(models.Model):
    product_name = models.CharField(max_length = 30, null=True)
    product_price = models.FloatField(default = 0, null=True)
    product_desc = models.CharField(max_length = 300, null=True)
    product_qty = models.PositiveIntegerField(default = 1, null=True)
    product_pic = ResizedImageField(upload_to = 'Product/',null=True, blank = True )

    def __str__(self):
        return self.product_name


class Order(models.Model):

    # def new_ref():
    #     not_unique = True
    #     while not_unique:
    #         unique_ref = random.randint(1000000000,9999999999)
    #         if not Order.objects.filter(order_unique_id = unique_ref):
    #             not_unique=False
    #     return str(unique_ref)    

    # order_unique_id = models.CharField(max_length=10,blank=True, editable=False, unique=True,default = new_ref)
    order_name = models.CharField(max_length = 30, null=True)
    order_items = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    order_creator = models.ForeignKey(User, on_delete=models.CASCADE)
    order_qty = models.IntegerField(default=1, null=True)
    order_details = models.TextField()
    payment_status = models.BooleanField(default=False)
    order_status_choice = (("New","New"),("Processing","Processing"),("Delivered","Delivered"),("Cancelled","Cancelled"))
    order_status = models.CharField(max_length=10,choices=order_status_choice, default="New")
    order_total_price = models.FloatField(null=True)
    order_date = models.DateField(default= timezone.now)
    delivery_date = models.DateField(null = True)

    
    def __str__(self):
        return self.order_name

    def placeOrder(self):
        self.save()
  
    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')


class Company(models.Model):
    business_name = models.CharField(max_length = 30, null=False)
    business_address = models.CharField(max_length= 300, null=False)
    business_orders = models.ForeignKey(Order,  on_delete=models.CASCADE, null=True)
    business_bank_account = models.CharField(max_length=30,null=True)
    business_website = models.URLField(default="https://www.",null=True)
    business_email = models.EmailField(null = True, default="business_name@gmail.com")
    business_contact_number = models.CharField(max_length=14,null=True)
    business_contact_person = models.CharField(max_length=80,null=False)
    business_status = models.CharField(max_length=50,null=False, default="National")
    
    def __str__(self):
        return self.business_name

report/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit, Div, HTML
class OrderFilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

            self.helper = FormHelper()
            self.helper.form_class = 'form-inline'
            self.helper.form_method = 'get'
            self.helper.form_show_lebels= True
            self.helper.layout = Layout(
                Div(
                    Div(HTML("""<h3>Report</h3>"""), css_class = 'form-inline col-md-2 mb-0 text-primary'),
                    Div('delivery_date',css_class='form-inline col-md-6 mb-0 h5 text-left text-black'),
                    Div(HTML("""<button class="mx-5 btn btn-md btn-primary">Search</button>"""),css_class='form-inline col-md-1 mb-0'),
                    css_class = 'row '
                    )
            )
            

report/views.py
from dataclasses import fields
from datetime import date, datetime
from itertools import product
from pyexpat import model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template import context
# from django.urls import reverse_lazy
# from django.db.models import fields
# from django.shortcuts import render
from django.views.generic import ListView, TemplateView, CreateView, UpdateView
from report.models import MonthlyBenifit
from user.models import Support
from sales.models import Company, Order, Product
from production.models import RawOrder, Supplier
from datetime import datetime
from .filters import OrderFilter
from django_filters.views import FilterView
# Create your views here.
#Dashboard part
class SearchView(LoginRequiredMixin,TemplateView):
    template_name = "sales/products.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Product.objects.filter(product_name__icontains = self.request.GET.get('search',''))
        return context

class DashboardView(LoginRequiredMixin ,TemplateView):
    template_name = "report/dashboard.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #Product Order
        context["all_product_order"] = len(Order.objects.all())
        context["new_product_order"] = len(Order.objects.filter(order_status = 'New'))
        context["processing_product_order"] = len(Order.objects.filter(order_status = 'Processing'))
        context["delivered_product_order"] = len(Order.objects.filter(order_status = 'Delivered'))
        #Raw Order Part
        context["all_raw_order"] = len(RawOrder.objects.all())
        context["new_raw_order"] = len(RawOrder.objects.filter(order_status = 'New'))
        #Support Part
        context["new_support_issues"] = len(Support.objects.filter(status = 'New') )

        #Montly order part
        this_month_first_day = datetime.today().date().replace(day=1)#Fisrt day of any month
        ThisMonthOrders = Order.objects.filter(order_date__gte = this_month_first_day).filter(order_status = 'Delivered' or 'Completed').values('order_total_price')
        Sum = 0
        for data in ThisMonthOrders:
            Sum = Sum+data['order_total_price']
        context['monthly_sell']=Sum

        #Montly Raw Order confirmed
        ThisMonthRawORders = RawOrder.objects.filter(delivery_date__gte = this_month_first_day).filter(order_status = 'Received' or 'Paid').values('total_price')
        Sum = 0
        for data in ThisMonthRawORders:Sum=Sum+data['total_price']
        context['monthly_buy'] = Sum

        #Earnings Overview line graph
        PreviousYear = datetime.today().year-1
        context['year'] = PreviousYear
        #ThisMonth = datetime.today().month
        Earnings = MonthlyBenifit.objects.filter(year = PreviousYear).values_list('month','earnings')
        for month, earnings in Earnings:context["month"+str(month)] = earnings
        
        return context

class SalesReportView(LoginRequiredMixin, TemplateView):
    template_name = "report/salesreport.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        yearmonth = self.request.GET.get('month')
        if yearmonth == None:
            yearmonth = datetime.today().replace(day=1,month=(datetime.today().month-1))
            context["object_list"] = Order.objects.filter(order_status = "Delivered").filter(delivery_date__gte = yearmonth)
        else:
            starting = str(yearmonth)+"-01"
            if yearmonth[5:] != "12":
                ending = str(yearmonth.replace(yearmonth[5:],str(int(yearmonth[5:])+1)))+"-01"
            else:
                ending=str(yearmonth.replace(yearmonth[:4],str(int(yearmonth[:4])+1)))+"-01"
                ending = ending.replace("12","01")
            context ["object_list"] = Order.objects.filter(order_status = "Delivered").filter(delivery_date__gte = starting).filter(delivery_date__lt = ending)
            context["monthly_sell"] = 0
            for price in context["object_list"]:
                context["monthly_sell"] = context["monthly_sell"] + price.order_total_price
            print(context["monthly_sell"])
        return context
    

class BuyerReportView(LoginRequiredMixin, ListView):
    model = Company
    template_name = "report/buyerreport.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = "object_list"
        return context
    

class ProductionReportView(LoginRequiredMixin, ListView):
    model = RawOrder
    template_name = "report/productionreport.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = "object_list"
        return context
    
class SupplierReportView(LoginRequiredMixin, ListView):
    model = Supplier
    template_name = "report/supplierreport.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = "object_list"
        return context

class MonthlyBenifitListView(LoginRequiredMixin, ListView):
    model = MonthlyBenifit
    template_name = "report/monthlybenifitlist.html"
    
class MonthlyBenifitCreateView(LoginRequiredMixin, CreateView):
    model = MonthlyBenifit
    fields = '__all__'
    template_name = "report/monthlybenifitcreate.html"

class MonthlyBenifitUpdateView(LoginRequiredMixin, UpdateView):
    model = MonthlyBenifit
    fields = '__all__'
    template_name = "report/monthlybenifitupdate.html"




    

templates/report/buyerreport.html
{% extends 'base.html' %}
{% block content %}
<input class="btn btn-primary" type="button" onClick="PrintDiv('divToPrint');" value="Print">
    <div class="widget-body">
					<div class="widget-main padding-24" id="divToPrint">
                    </div>
                </div>
{% endblock %}
{% block js %} 
    
function PrintDiv(){ 
    var printContents = document.getElementById('divToPrint').innerHTML; 
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents
    } 
{% endblock %}

templates/report/dashboard.html
{% extends 'base.html' %} {% block title %} Dashboard {% endblock title %} 
{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
  

</div>

<!-- Content Row -->
<div class="row">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-primary text-uppercase mb-1"
            >
              Monthly Buy (Raw Orders)
            </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ monthly_buy }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-success text-uppercase mb-1"
            >
              Monthly Sell
            </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{monthly_sell}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- New Raw Order -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
              New Raw Orders
            </div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                  {{ new_raw_order}}
                </div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div
                    class="progress-bar bg-info"
                    role="progressbar"
                    style="width: 50%"
                    aria-valuenow="90"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Pending Requests Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-warning text-uppercase mb-1"
            >
              New Support Issues
            </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">
              {{new_support_issues}}
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-comments fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Content Row -->

<div class="row">
  <!-- Area Chart -->
  <div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
      >
        <h6 class="m-0 font-weight-bold text-primary">Earnings Overview at {{year}}</h6>
        <div class="dropdown no-arrow">
          <a
            class="dropdown-toggle"
            href="#"
            role="button"
            id="dropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
          </a>
          <div
            class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
            aria-labelledby="dropdownMenuLink"
          >
            <div class="dropdown-header">Dropdown Header:</div>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-area">
          <canvas id="myAreaChart"></canvas>
        </div>
      </div>
    </div>
  </div>

  <!-- Pie Chart -->
  <div class="col-xl-4 col-lg-5">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
      >
        <h6 class="m-0 font-weight-bold text-primary">
          All Orders
        </h6>
        <div class="dropdown no-arrow">
          <a
            class="dropdown-toggle"
            href="#"
            role="button"
            id="dropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
          </a>
          <div
            class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
            aria-labelledby="dropdownMenuLink"
          >
            <div class="dropdown-header">Actions</div>
            <a class="dropdown-item" href="{% url 'orders_list' %}"
              >Order list</a
            >
          </div>
        </div>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-pie pt-4 pb-2">
          <canvas id="myPieChart"></canvas>
        </div>
        <div class="mt-4 text-center small">
          <span class="mr-2">
            <i class="fas fa-circle text-primary"></i> New</span
          >
          <span class="mr-2">
            <i class="fas fa-circle text-success"></i> Processing</span
          >
          <span class="mr-2">
            <i class="fas fa-circle text-info"></i> Delivered</span
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
    Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
    Chart.defaults.global.defaultFontColor = '#858796';
    var cty = document.getElementById("myPieChart");
    var New = "{{ new_product_order }}";
    var Processing = "{{ processing_product_order }}";
    var Delivered = "{{ delivered_product_order }}";
    var myPieChart = new Chart(cty, {
        type: 'doughnut',
        data: {
            labels: ["New", "Processing", "Deliverd"],
            datasets: [{
                data: [New, Processing, Delivered],
                backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc'],
                hoverBackgroundColor: ['#2e59e9', '#17a673', '#2c9faf'],
                hoverBorderColor: "rgba(234, 236, 244, 1)",
            }],
        },
        options: {
            maintainAspectRatio: false,
            tooltips: {
                backgroundColor: "rgb(255,255,255)",
                bodyFontColor: "#858796",
                borderColor: '#dddfeb',
                borderWidth: 1,
                xPadding: 15,
                yPadding: 15,
                displayColors: false,
                caretPadding: 10,
            },
            legend: {
                display: false
            },
            cutoutPercentage: 80,
        },
    });

    
// Area Chart Example
var ctx = document.getElementById("myAreaChart");
var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        datasets: [{
            label: "Earnings",
            lineTension: 0.3,
            backgroundColor: "rgba(78, 115, 223, 0.05)",
            borderColor: "rgba(78, 115, 223, 1)",
            pointRadius: 3,
            pointBackgroundColor: "rgba(78, 115, 223, 1)",
            pointBorderColor: "rgba(78, 115, 223, 1)",
            pointHoverRadius: 3,
            pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
            pointHoverBorderColor: "rgba(78, 115, 223, 1)",
            pointHitRadius: 10,
            pointBorderWidth: 2,
            data: [{{ month1 }}, {{ month2 }}, {{ month3 }}, {{ month4 }}, {{ month5 }}, {{ month6 }}, {{ month7 }}, {{ month8 }}, {{ month9 }}, {{ month10 }}, {{month11}}, {{month12}}],
        }],
    },
    options: {
        maintainAspectRatio: false,
        layout: {
            padding: {
                left: 10,
                right: 25,
                top: 25,
                bottom: 0
            }
        },
        scales: {
            xAxes: [{
                time: {
                    unit: 'date'
                },
                gridLines: {
                    display: false,
                    drawBorder: false
                },
                ticks: {
                    maxTicksLimit: 7
                }
            }],
            yAxes: [{
                ticks: {
                    maxTicksLimit: 5,
                    padding: 10,
                    // Include a dollar sign in the ticks
                    callback: function(value, index, values) {
                        return '$' + number_format(value);
                    }
                },
                gridLines: {
                    color: "rgb(234, 236, 244)",
                    zeroLineColor: "rgb(234, 236, 244)",
                    drawBorder: false,
                    borderDash: [2],
                    zeroLineBorderDash: [2]
                }
            }],
        },
        legend: {
            display: false
        },
        tooltips: {
            backgroundColor: "rgb(255,255,255)",
            bodyFontColor: "#858796",
            titleMarginBottom: 10,
            titleFontColor: '#6e707e',
            titleFontSize: 14,
            borderColor: '#dddfeb',
            borderWidth: 1,
            xPadding: 15,
            yPadding: 15,
            displayColors: false,
            intersect: false,
            mode: 'index',
            caretPadding: 10,
            callbacks: {
                label: function(tooltipItem, chart) {
                    var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                    return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
                }
            }
        }
    }
});
{% endblock %}

templates/report/monthlybenifitcreate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}
Earnigns
{% endblock title %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">New Monthly Earnings</h1>
        </div>          
 
        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Enter Earnings!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-block">Create</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="/">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/report/monthlybenifitlist.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<div class="">
    <div class="row">
        <div class="col">
            <div class="card card-custom gutter-b ">
                <div class="card-header d-flex">
                    <div class="card-title">
                        <h3 class="card-label">Enter Montly Earnings</h3>
                    </div>
                    {% if user.groups.name == 'Admin' %}
                    <div class="card-toolbar ml-auto">
                        <a href="{% url 'monthlybenifit_create' %}" class="btn btn-info">Add New</a>
                    </div>
                    {% endif %}
                    
                </div>
                {% if object_list %}
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table text-center" id="kt_datatable" style="width: 100%">
                            <thead>
                                <tr >
                                    <th>Serials</th>
                                    <th>Year</th>
                                    <th>Month</th>
                                    <th>Earnings</th>
                                    <th style="width: 180px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                {% for record in object_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</i></a></td>
                                    <td>{{ record.year }}</td>
                                    <td>{{ record.month }}</td>
                                    <td>{{ record.earnings }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-light-warning"
                                            href="{% url 'monthlybenifit_update' record.pk %}"><i class="far fa-edit btn btn-success"></i></i>
                                        </a>
                                        
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!--end: Datatable-->
                    {% else %}
                    {% include 'includes/no_data_found.html' %}
                    {% endif %}
                </div>
                <div class="card-footer">
                    {% comment %} {% include 'includes/pagination.html' %} {% endcomment %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/report/monthlybenifitupdate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Update Monthly Earning</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Update !!!</h1>
                  </div>
                  <form method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-block">Update</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'product_list' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.con
{% endblock %}

templates/report/productionreport.html
{% extends 'base.html' %}
{% block content %}
<input class="btn btn-primary" type="button" onClick="PrintDiv('divToPrint');" value="Print">
    <div class="widget-body">
					<div class="widget-main padding-24" id="divToPrint">
                    </div>
                </div>
{% endblock %}
{% block js %} 
    
function PrintDiv(){ 
    var printContents = document.getElementById('divToPrint').innerHTML; 
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents
    } 
    
{% endblock %}

templates/report/supplierreport.html
{% extends 'base.html' %}
{% block content %}
<input class="btn btn-primary" type="button" onClick="PrintDiv('divToPrint');" value="Print">
    <div class="widget-body">
					<div class="widget-main padding-24" id="divToPrint">
                    </div>
                </div>
{% endblock %}
{% block js %} 
    
function PrintDiv(){ 
    var printContents = document.getElementById('divToPrint').innerHTML; 
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents
    } 
    
{% endblock %}